java.release=8

product.max.file=200
test.max.file=300
harness.max.file=300
tool.max.file=300

modules=core,modloader,stationapi
module.core.roots=core
module.core.dependencies=
module.modloader.roots=modloader/aero
module.modloader.dependencies=core
module.stationapi.roots=stationapi/src/main/java
module.stationapi.dependencies=core

test.roots=modloader/tests/aero
tool.roots=tools
test.libs=modloader/tests/libs/junit-4.13.2.jar,modloader/tests/libs/hamcrest-core-1.3.jar
